FROM golang:latest

RUN go install github.com/silenceper/gowatch@latest

RUN pip install --upgrade pip poetry

RUN mkdir /nickelmod
WORKDIR /nickelmod

COPY go.mod go.sum ./

RUN go mod tidy

CMD ["gowatch"]
